---
basic:
  - name: Title
    definition: Human-readable name
    json: title
    rdfa: dct:title
    
  - name: Description
    definition: Human-readable description
    json: description
    rdfa: dct:description

  - name: Documentation URL
    definition: URL to documentation
    json: datadictionary
    rdfa: dcat:dataDictionary
    type: url
    
  - name: URL
    definition: URL to dataset or API
    json: accessurl
    rdfa: dcat:accessURL
    type: url
    
  - name: Tags
    definition: Keywords describing tags
    json: keywords
    rdfa: dcat:keywords
    type: text

  - name: License
    definition: Licenese under which the dataset is published
    json: license
    rdfa: dct:license

  - name: Public
    definition: Whether the dataset is public
    json: public
    rdfa: xsd:boolean
    type: boolean
    
  - name: Agency
    definition: Publishing Agency
    json: organization
    rdfa: foaf:Organization

expanded: